### PR TITLE
Update admin dashboard

### PR DESCRIPTION
**Pull request by RDelorier**
Update admin dashboard to make it easier to view usage per user.

I don't know how to upload to that "cloud.github" for hosting gifs so here is a link...
[Dashboard Gif](http://d.pr/i/10w1M)

### CODE REVIEW

**Comment by RDelorier** [comment]
@mattstauffer hopefully this is helpful :)

**Comment by mattstauffer** [comment]
@RDelorier man. Lots of great work in this. Thank you! Looking forward to trying it out!

**Comment by RDelorier** [comment]
You're welcome, man I gotta say working on an app with decent test coverage makes stuff a lot easier. This is definitely helping me sharpen up some stuff so thanks for allowing contributions :+1:

**Comment by mattstauffer** [comment]
@RDelorier :) glad to hear it!

**Comment by RDelorier** [comment]
haha, just figured out how to upload to the cloud.github.com, drag and drop zzz next time!

**Pull request merged**
