### PR TITLE
Style tweaks and Mobile Optimization

### PR DESCRIPTION
**Pull request by JacobBennett**
- Included a hero image at a reduced size for mobile viewers (still 2x for retina)
- Fixed an issue where hero section was overflowing viewport size
- Increased hit size on nav for mobile visitors

**Note:** I decided to use `calc` to determine the height for the `.page-home-hero` only after considering [CanIUse](http://caniuse.com/#feat=calc) stats. Being that the rule using `calc` will only apply to desktop browsers, I would assume coverage for it's use is sufficient.

### CODE REVIEW

**Comment by mattstauffer** [comment]
Thanks for the PR! a few notes:
- I like using the smaller image at mobile sizes.
- I don't like that this makes the hero full height. I like seeing some of the FAQ peek up so you can know there's more to scroll to. This is overkill:

image
- I actually don't like the mobile image being centered; it makes the text hard to read. I liked it being offset. This PR:

image

The current live site:

image

Finally, the smaller image looks super artifact-y. I'm worried it might be a little too compressed. Have you taken a look in a retina iPhone (e.g. 6s) to see how it looks? Thanks!

**Comment by JacobBennett** [comment]
Thanks for the feedback! Agree that the whole viewport is overkill. I think I was considering when you have a screen smaller than 912px and you had to scroll to get past the hero and to the FAQ. Maybe I'll throw a max-height on there of 912px so it wouldn't take over the whole viewport... I'll have to play around and see what I can come up with on that. 

As far as compression on the image, I unfortunately still have my 5s... should be getting 6s in the coming week though so then I can see how terrible the image looks :smile:

**Comment by JacobBennett** [comment]
Hey @mattstauffer, made the requested changes.
- Bumped Quality on smaller hero image for retina displays
- Reset `background-position` for hero image on mobile to offset background for better legibility.
- Added a max-size to the hero image on desktop
- Ran `gulp --production` to minify all css assets

Related to the `max-size` item above, this may seem like overkill here, but hear me out.

The setup as it is in this PR allows the following
- Hero height will match viewport height for screens smaller than `912px` (instead of overflowing it)
- Hero height will max out at `912px` for screens with viewport larger than that (this was the default before)
- Hero height will always be at least `650px` to prevent the content overflowing the hero

The other option we have would be to use `calc()` to always show a little of the faq peeking up from the bottom so the user knows there is more to the page... that or we could do something awesome like

6a8157dd-a55a-4cc2-a710-84d39521668a

http://jetlag.photos/

**Comment by mattstauffer** [comment]
yassssssss

@JacobBennett I owe you. You did fantastic work on this. Thank you my friend!

**Pull request merged**
